# Generated by Django 3.1.11 on 2021-05-28 06:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IceCream",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cone_wafer",
                    models.CharField(
                        choices=[
                            ("plain", "Plain"),
                            ("chocolate", "Chocolate"),
                            ("waffle", "Waffle"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "base_flavour",
                    models.CharField(
                        choices=[
                            ("vanilla", "Vanilla"),
                            ("chocolate", "Chocolate"),
                            ("mango", "Mango"),
                            ("strawberry", "Strawberry"),
                            ("coconut", "Coconut"),
                        ],
                        max_length=150,
                    ),
                ),
                (
                    "toppings",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Tutti Frutti", "Tutti Frutti"),
                                ("Chocolate Chips", "Chocolate Chips"),
                                ("Roasted Almonds", "Roasted Almonds"),
                            ],
                            max_length=150,
                        ),
                        size=None,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icecreams",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
