# Generated by Django 3.1.11 on 2021-05-27 15:08

from icecream.models import BaseFlavour, ConeWafer
from django.db import migrations


def seed(apps, schema_editor):
    ConeWafer = apps.get_model("icecream", "conewafer")
    BaseFlavour = apps.get_model("icecream", "baseflavour")
    Topping = apps.get_model("icecream", "topping")

    ConeWafer.objects.bulk_create(
        [ConeWafer(name="Plain"), ConeWafer(name="Chocolate"), ConeWafer(name="Waffle")]
    )
    BaseFlavour.objects.bulk_create(
        [
            BaseFlavour(name="Vanilla"),
            BaseFlavour(name="Chocolate"),
            BaseFlavour(name="Mango"),
            BaseFlavour(name="Strawberry"),
            BaseFlavour(name="Coconut"),
        ]
    )
    Topping.objects.bulk_create(
        [
            Topping(name="Tutti Fruti"),
            Topping(name="Chocolate Chips"),
            Topping(name="Roasted Almonds"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("icecream", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            seed,
        ),
    ]
