# Generated by Django 3.1.11 on 2021-05-27 21:36

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remarks', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed')], default='created', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
